FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY cert.pem /etc/nginx/certs/cert.pem
COPY key.pem  /etc/nginx/certs/key.pem

EXPOSE 80 443